from e2b import CodeInterpreter

from dotenv import load_dotenv

load_dotenv()

sandbox = CodeInterpreter(api_key="e2b_b56f942630ecf19f93733f107fe2466d0cba52f0")

# 2. Get code that was generated by LLM and run it
llm_generated_python_code = """def hello():
    return 1
hello()""" 

# `artifacts` are chart files created by matplotlib
stdout, stderr, artifacts = sandbox.run_python(llm_generated_python_code)
print(stderr)


print(stdout)
# 3. Retrieve chart files:
for artifact in artifacts:
  # Now you can save this file, send it to frontend, or anything else
  downloaded_chart = artifact.download()
  print(downloaded_chart)

# 4. Close sandbox
sandbox.close()
