dummy1 = {
    "instance_id": ["1", "2", "3", "4", "5", "6"],
    "base_commit": [
        "dd707f99dd21d68131c1b97de5c8820f3590cb97",
        "9074085a59033e70ab8003df79e4e718cb74d6eb",
        "7fa35d6a1d91630667137ac8eb19493921f031b6",
        "db82a3eb3011acb6ae7cf288dd9b42cd5781b9f5",
        "7327d0e9d8069366daf6c6d378df27a604425332",
        "e05215fc4740df3fa1ac9f00b7285a0c9495eeec",
    ],
    "environment_setup_commit": [
        "dd707f99dd21d68131c1b97de5c8820f3590cb97",
        "9074085a59033e70ab8003df79e4e718cb74d6eb",
        "7fa35d6a1d91630667137ac8eb19493921f031b6",
        "db82a3eb3011acb6ae7cf288dd9b42cd5781b9f5",
        "7327d0e9d8069366daf6c6d378df27a604425332",
        "e05215fc4740df3fa1ac9f00b7285a0c9495eeec",
    ],
    "problem_statement": [
        "The magic.main.invert_string function should reverse any string passed to it. But it doesn't. Please fix it.",
        "`wierd_fun` is probably seams to return incorrect values sometimes",
        "`wierd_fun` calculates the fibonacci sequence incorrectly",
        "`fibonacci_substraction` is such a cool function for the negative fibonacci numbers, but when I run it, I think it's not working properly. For example, fibonacci_substraction(1) should probably return 1, but it doesn't.",
        "What is the `get_date` function? The format for the first of January 2001 at 01:01:01 is `01-01-01 01:01:01` is expected, but the other results are off. Can you check the tests and please fix the implementation? I have no idea where to start or what the problem is",
        "The brainfuck interpreter is awesome, I always wanted to use these esoteric languages. But I am uncertain, if the function is implemented perfectly. I have run some tests and I personally think the pointers should be initialized with 0 instead of 1. But that causes some issues to fail. This is wierd.",
    ],
    "FAIL_TO_PASS": [
        "['test_string_inversion_1 (test.test_main.test_string_inversion_1)', 'test_string_inversion_2 (test.test_main.test_string_inversion_2)']",
        "['test_fibonacci_1 (test.test_main.test_fibonacci_1)', 'test_fibonacci_2 (test.test_main.test_fibonacci_2)']",
        "['test_fibonacci_1 (test.test_main.test_fibonacci_1)', 'test_fibonacci_2 (test.test_main.test_fibonacci_2)']",
        "['test_fibonacci_substraction_1 (test.test_main.test_fibonacci_substraction_1)', 'test_fibonacci_substraction_2 (test.test_main.test_fibonacci_substraction_2)']",
        "['test_date_1 (test.test_main.test_date_1)', 'test_date_2 (test.test_main.test_date_2)']",
        "['test_brainfuck_1 (test.test_main.test_brainfuck_1)', 'test_brainfuck_1 (test.test_main.test_brainfuck_1)']",
    ],
    "repo": [
        "gstenzel/ignore-this-dummy",
        "gstenzel/ignore-this-dummy",
        "gstenzel/ignore-this-dummy",
        "gstenzel/ignore-this-dummy",
        "gstenzel/ignore-this-dummy",
        "gstenzel/ignore-this-dummy",
    ],
    "test_patch": ["[]", "[]", "[]", "[]", "[]", "[]"],
    "text": [
        "Context\n...\n[start of magic/main.py]\n...\n[end of magic/main.py]\n...\n[start of magic/__init__.py]\n...\n[end of magic/__init__.py][start of magic/test/test_main.py]\n...\n[end of magic/test/test_main.py]\n...\nContext\n...\n",
        "Context\n...\n[start of magic/main.py]\n...\n[end of magic/main.py]\n...\n[start of magic/__init__.py]\n...\n[end of magic/__init__.py][start of magic/test/test_main.py]\n...\n[end of magic/test/test_main.py]\n...\nContext\n...\n",
        "Context\n...\n[start of magic/main.py]\n...\n[end of magic/main.py]\n...\n[start of magic/__init__.py]\n...\n[end of magic/__init__.py][start of magic/test/test_main.py]\n...\n[end of magic/test/test_main.py]\n...\nContext\n...\n",
        "Context\n...\n[start of magic/main.py]\n...\n[end of magic/main.py]\n...\n[start of magic/__init__.py]\n...\n[end of magic/__init__.py][start of magic/test/test_main.py]\n...\n[end of magic/test/test_main.py]\n...\nContext\n...\n",
        "Context\n...\n[start of magic/main.py]\n...\n[end of magic/main.py]\n...\n[start of magic/__init__.py]\n...\n[end of magic/__init__.py][start of magic/test/test_main.py]\n...\n[end of magic/test/test_main.py]\n...\nContext\n...\n",
        "Context\n...\n[start of magic/main.py]\n...\n[end of magic/main.py]\n...\n[start of magic/__init__.py]\n...\n[end of magic/__init__.py][start of magic/test/test_main.py]\n...\n[end of magic/test/test_main.py]\n...\nContext\n...\n",
    ],
}

dummy2 = {
    "instance_id": ["1", "2", "3", "4", "5"],
    "base_commit": [
        "ccc3d719a0bd5e5564e6faf4d3d87d6d35c8ed7c",
        "cac6fa0bb7d58bd9e99b26e506b3c48be34449c0",
        "1a469461d1ed6c58ce0dfba48e7b93e31b7817aa",
        "f2df51fee8d338c6d718f015f3fddd2c52024a58",
        "d8f0050fa18a478c2a4509fe4099dbbccc9dbc6f",
    ],
    "environment_setup_commit": [
        "ccc3d719a0bd5e5564e6faf4d3d87d6d35c8ed7c",
        "cac6fa0bb7d58bd9e99b26e506b3c48be34449c0",
        "1a469461d1ed6c58ce0dfba48e7b93e31b7817aa",
        "f2df51fee8d338c6d718f015f3fddd2c52024a58",
        "d8f0050fa18a478c2a4509fe4099dbbccc9dbc6f",
    ],
    "problem_statement": [
        "The existing code fetches the collection each time the code is called. I've added the function save_collection_to_json, so it stores the collection as a JSON in the path specified, but it does not store anything as of now. Fix the implementation of the function.",
        "save_collection_to_json overwrites the file, if it already exists. Firstly I wanted to check if the collection given has valid syntax, then check for the file and if present, check when it was created. When the file is not older than 24 hours, load the collection from the json file. Additionally, let the function return True if the file was changed, False otherwise.",
        "For now, the collection data is only fetched and stored. My function called split_artist_release_percentage is not properly working as of now. It should return a dataframe containing the top artists in the collection with their percentage and the rest of the artists with their accumulated percentage",
        "We have the function visualize_artist_release_percentage in place, which should visualize the top_k_artists in a pie chart using mathplotlib. As if now, this is not working and returning errors",
        "Fix the function called list_artist_releases which should print all releases in the collection in a table view if no artist is specified. If an artist is specified, then only print the releases by this artist.",
    ],
    "FAIL_TO_PASS": [
        "['test_save_collection_to_json (test.test_fetch_process_collection.test_save_collection_to_json)', 'test_save_collection_to_json_nested (test.test_fetch_process_collection.test_save_collection_to_json_nested)', 'test_save_collection_to_json_empty (test.test_fetch_process_collection.test_save_collection_to_json_empty)', 'test_save_collection_to_json_file_error (test.test_fetch_process_collection.test_save_collection_to_json_file_error)', 'test_save_collection_to_json_invalid_json (test.test_fetch_process_collection.test_save_collection_to_json_invalid_json)']",
        "['test_save_collection_new_file (test.test_fetch_process_collection.test_save_collection_new_file)', 'test_save_collection_overwrite_old_file (test.test_fetch_process_collection.test_save_collection_overwrite_old_file)', 'test_save_collection_do_not_overwrite_recent_file (test.test_fetch_process_collection.test_save_collection_do_not_overwrite_recent_file)', 'test_save_collection_exact_24_hours (test.test_fetch_process_collection.test_save_collection_exact_24_hours)']",
        "['test_split_artist_release_percentage_normal (test.test_fetch_process_collection.test_split_artist_release_percentage_normal)', 'test_split_artist_release_percentage_empty_list (test.test_fetch_process_collection.test_split_artist_release_percentage_empty_list)', 'test_split_artist_release_percentage_not_list (test.test_fetch_process_collection.test_split_artist_release_percentage_not_list)', 'test_split_artist_release_percentage_no_artist_column (test.test_fetch_process_collection.test_split_artist_release_percentage_no_artist_column)', 'test_split_artist_release_percentage_all_unique (test.test_fetch_process_collection.test_split_artist_release_percentage_all_unique)', 'test_split_artist_release_percentage_no_others (test.test_fetch_process_collection.test_split_artist_release_percentage_no_others)', 'test_split_artist_release_percentage_large_top_number (test.test_fetch_process_collection.test_split_artist_release_percentage_large_top_number)', 'test_split_artist_release_percentage_different_top_numbers[1] (test.test_fetch_process_collection.test_split_artist_release_percentage_different_top_numbers[1])', 'test_split_artist_release_percentage_different_top_numbers[2] (test.test_fetch_process_collection.test_split_artist_release_percentage_different_top_numbers[2])', 'test_split_artist_release_percentage_different_top_numbers[3] (test.test_fetch_process_collection.test_split_artist_release_percentage_different_top_numbers[3])', 'test_split_artist_release_percentage_single_artist (test.test_fetch_process_collection.test_split_artist_release_percentage_single_artist)']",
        "['test_visualize_artist_release_percentage_normal (test.test_fetch_process_collection.test_visualize_artist_release_percentage_normal)', 'test_visualize_artist_release_empty_dataframe (test.test_fetch_process_collection.test_visualize_artist_release_empty_dataframe)', 'test_visualize_artist_release_percentage_missing_columns (test.test_fetch_process_collection.test_visualize_artist_release_percentage_missing_columns)', 'test_visualize_artist_release_percentage_various_inputs (test.test_fetch_process_collection.test_visualize_artist_release_percentage_various_inputs)', 'test_visualize_artist_release_percentage_plot_details (test.test_fetch_process_collection.test_visualize_artist_release_percentage_plot_details)']",
        "['test_list_artist_releases_all (test.test_fetch_process_collection.test_list_artist_releases_all)', 'test_list_artist_releases_specific_artist (test.test_fetch_process_collection.test_list_artist_releases_specific_artist)', 'test_list_artist_releases_nonexistent_artist (test.test_fetch_process_collection.test_list_artist_releases_nonexistent_artist)', 'test_list_artist_releases_empty_collection (test.test_fetch_process_collection.test_list_artist_releases_empty_collection)', 'test_list_artist_releases_output_format (test.test_fetch_process_collection.test_list_artist_releases_output_format)', 'test_list_artist_releases_return_value (test.test_fetch_process_collection.test_list_artist_releases_return_value)', 'test_list_artist_releases_various_artists (test.test_fetch_process_collection.test_list_artist_releases_various_artists)']",
    ],
    "repo": [
        "bodhinsky/apicurl",
        "bodhinsky/apicurl",
        "bodhinsky/apicurl",
        "bodhinsky/apicurl",
        "bodhinsky/apicurl",
    ],
    "test_patch": ["[]", "[]", "[]", "[]", "[]"],
    "text": [
        "Context\n...\n[start of main.py]\n...\n[end of main.py]\n...\n[start of apicurl/fetch_process_collection.py]\n...\n[end of apicurl/fetch_process_collection.py][start of test/test_fetch_process_collection.py]\n...\n[end of test/test_fetch_process_collection.py]\n...\nContext\n...\n",
        "Context\n...\n[start of main.py]\n...\n[end of main.py]\n...\n[start of apicurl/fetch_process_collection.py]\n...\n[end of apicurl/fetch_process_collection.py][start of test/test_fetch_process_collection.py]\n...\n[end of test/test_fetch_process_collection.py]\n...\nContext\n...\n",
        "Context\n...\n[start of main.py]\n...\n[end of main.py]\n...\n[start of apicurl/fetch_process_collection.py]\n...\n[end of apicurl/fetch_process_collection.py][start of test/test_fetch_process_collection.py]\n...\n[end of test/test_fetch_process_collection.py]\n...\nContext\n...\n",
        "Context\n...\n[start of main.py]\n...\n[end of main.py]\n...\n[start of apicurl/fetch_process_collection.py]\n...\n[end of apicurl/fetch_process_collection.py][start of test/test_fetch_process_collection.py]\n...\n[end of test/test_fetch_process_collection.py]\n...\nContext\n...\n",
        "Context\n...\n[start of main.py]\n...\n[end of main.py]\n...\n[start of apicurl/fetch_process_collection.py]\n...\n[end of apicurl/fetch_process_collection.py][start of test/test_fetch_process_collection.py]\n...\n[end of test/test_fetch_process_collection.py]\n...\nContext\n...\n",
    ],
}
